### ISSUE TITLE
Access to the path is denied since V1.0.19

### ISSUE THREAD

**Issue by jpdsc** [darkalfx/requestrr#106]
Since version V1.0.19; bot does not react to commands in chat.
Below in error in log:

```
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while restarting the bot: Access to the path '/app/slashcommandsbuilder-cb821a7a-ee33-4bf8-ac2d-5514c8b7dbc8.dll' is denied.
      System.IO.IOException: Access to the path '/app/slashcommandsbuilder-cb821a7a-ee33-4bf8-ac2d-5514c8b7dbc8.dll' is denied.
       ---> System.UnauthorizedAccessException: Access to the path '/app/slashcommandsbuilder-cb821a7a-ee33-4bf8-ac2d-5514c8b7dbc8.dll' is denied.
       ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
         at System.IO.File.Create(String path)
         at Roslyn.Utilities.FileUtilities.CreateFileStreamChecked(Func`2 factory, String path, String paramName)
         --- End of inner exception stack trace ---
         at Roslyn.Utilities.FileUtilities.CreateFileStreamChecked(Func`2 factory, String path, String paramName)
         at Microsoft.CodeAnalysis.FileSystemExtensions.Emit(Compilation compilation, String outputPath, String pdbPath, String xmlDocPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
         at Requestrr.WebApi.RequestrrBot.SlashCommandBuilder.Build(ILogger logger, DiscordSettings settings) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\SlashCommands\SlashCommandBuilder.cs:line 54
         at Requestrr.WebApi.RequestrrBot.ChatBot.RestartBot(DiscordSettings previousSettings, DiscordSettings newSettings, HashSet`1 currentGuilds) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 167
         at Requestrr.WebApi.RequestrrBot.ChatBot.<Start>b__20_0() in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 95
```

**Comment by jimmyshadow1** [comment]
Same here, running on Docker on Unraid

**Comment by jpdsc** [comment]
Fix from Darkalfx for official image:

```
Kick the bot from your server

Then use this link
https://discord.com/api/oauth2/authorize?client_id=YOURAPPLICATIONID&permissions=522304&scope=bot%20applications.commands

Replace YOURAPPLICATIONID by your application ID for your bot
That will give it permission, you might need to restart the bot after doing this
```

For Hotio image > update the image
For Linuxserver.io > TBD

**Comment by jimmyshadow1** [comment]
Using Hotio image, can confirm updating it fixed the issue. Thanks!

**Comment by topher587** [comment]
Also running darkalfx/requestrr:latest in Unraid. 
1.0.20 current version. 

Bot is unresponsive to chat commands since 1.0.19.
Responsive management UI on :4545.

Attempted to kick and re-invite with 522304 permissions link, no change.

**Comment by darkalfx** [comment]
The linuxserver image should now work correctly as well!

**Comment by darkalfx** [comment]
> 
> 
> Also running darkalfx/requestrr:latest in Unraid. 1.0.20 current version.
> 
> Bot is unresponsive to chat commands since 1.0.19. Responsive management UI on :4545.
> 
> Attempted to kick and re-invite with 522304 permissions link, no change.

Make sure to use the invite link found in the web portal in version 1.0.20 as it was broken prior to this version.

Kick the bot from your server, re-invite it using that link and once its joined your server, restart it just to make extra sure.

It should be smooth sailing!

**Comment by darkalfx** [comment]
I am closing this issue as all the main images should be fixed by now.

**Comment by topher587** [comment]
I redeployed the bot and encountered the same problem, and never could never get response to !ping which was my primary testing method. 

This seems to have likely stemmed from dropping support for the command prefix and !command syntax as of V1.0.19 and moving exclusively to the /command syntax. 

The install guide now has references to the old "command prefix" that no longer exists, and still suggests using !ping. 

Thanks for the tool, now just to retrain my users!
