### ISSUE TITLE
Error Registering Application commands since v1.0.19

### ISSUE THREAD

**Issue by BeLess** [darkalfx/requestrr#107]
I've updated requestrr to the latest version (1.0.19) to make use of the slash commands, but now the entire bot seems broken, and I receive the following stack trace when attempting to test it:

```
There was an error registering application commands
DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass38_0.<<RegisterCommands>b__0>d.MoveNext()
```

Even `!ping` receives no response. Discord configuration seems fine. The "test settings" button reports no issues. Bot settings haven't changed.

Running on Windows 10.

**Comment by dhaos21** [comment]
https://github.com/darkalfx/requestrr/issues/106

**Comment by BeLess** [comment]
Oh, didn't realize they were the same root issue. That did indeed fix this, Thanks!
