### ISSUE TITLE
Bot stopped responding to commands

### ISSUE THREAD

**Issue by josephfriesen** [darkalfx/requestrr#108]
Hey, I'm not sure what happened but the requestrr-bot suddenly stopped responding to commands (!movie, !help) in our server. After kicking and reinstalling/inviting against still having the same issue. Sorry if that's an awfully vague description of the problem, any help figuring out what went wrong would be much appreciated, thank you.

**Comment by mynvnow** [comment]
Same issue here. I am on the linuxserver.io's latest image (updated 19 hours ago) 

`[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 90-custom-folders: executing... 

[cont-init.d] 90-custom-folders: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]

      Using an in-memory repository. Keys will not be persisted to storage.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]

      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]

      No XML encryptor configured. Key {2cbe8d05-ac92-4643-bb1a-1bbd9262608c} may be persisted to storage in unencrypted form.

warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]

      Bot configuration changed: restarting bot

Hosting environment: Production

Content root path: /app/requestrr/bin

Now listening on: http://[::]:4545

Application started. Press Ctrl+C to shut down.

warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]

      Bot has been restarted.

warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]

      Bot configuration changed: restarting bot

warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]

      Bot has been restarted.

[2021-09-28 22:47:58 -05:00] [0   /            ] [Crit ] There was an error registering application commands

DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 403

   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)

   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass38_0.<<RegisterCommands>b__0>d.MoveNext()

warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]

      Failed to determine the https port for redirect.

[2021-09-28 22:51:59 -05:00] [101 /Startup     ] [Info ] DSharpPlus, version 4.2.0-nightly-01008`

**Comment by Motophan** [comment]
Same

**Comment by jariz** [comment]
I had this same problem. I think it's because they require different permissions now because of the slash commands.
I 'resolved' this eventually by creating a new app and reinviting it.
Keep in mind that you now need to request `/request tv title` and `/request movie title` instead of the old !tv and !movie commands - these don't work anymore.

**Comment by kevinoconnor7** [comment]
I resolved this by removing the integration on all applicable servers, restarting requestrr, and then reinviting the bot using the link from the Web UI. I did not have to create a new app/bot.
