### ISSUE TITLE
Error since Sonarr was updated to version 3.0.6.1335

### ISSUE THREAD

**Issue by ElYoM** [darkalfx/requestrr#110]
Hello,

Since Sonarr has been updated to version 3.0.6.1335 on 29/09/2021, I can't make requests for TV series anymore. I have the following error messages in the Docker container logs. I would like to point out that it still works perfectly for movies with Radarr...
Thank you in advance for your help.

`fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while sending help command: Sequence contains no matching element
      System.InvalidOperationException: Sequence contains no matching element
         at System.Linq.ThrowHelper.ThrowNoMatchException()
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordTvShowUserInterface.AddPreviousDropdownsAsync(TvShow tvShow, DiscordWebhookBuilder builder) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordTvShowUserInterface.cs:line 268
        at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordTvShowUserInterface.WarnAlreadySeasonAlreadyRequestedAsync(TvShow tvShow, TvSeason requestedSeason) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordTvShowUserInterface.cs:line 215
         at Requestrr.WebApi.RequestrrBot.TvShows.TvShowRequestingWorkflow.HandleTvShowSelectionAsync(Int32 tvDbId) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\TvShows\TvShowRequestingWorkflow.cs:line 102
         at Requestrr.WebApi.RequestrrBot.TvShows.TvShowRequestingWorkflow.SearchTvShowAsync(String tvShowName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\TvShows\TvShowRequestingWorkflow.cs:line 47`

**Comment by jpdsc** [comment]
Also happens on movies. For example, try and search for Queenpins
```
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while sending help command: Sequence contains no matching element
      System.InvalidOperationException: Sequence contains no matching element
         at System.Linq.ThrowHelper.ThrowNoMatchException()
         at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.DisplayMovieDetailsAsync(Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 74
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.HandleMovieSelectionAsync(Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 85
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 43
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle(InteractionContext ctx, String movieTitle)
```

**Comment by ElYoM** [comment]
Indeed, I see the same problem with the Queenpins movie but it works with Deadpool 2 for example... Weird...

**Comment by darkalfx** [comment]
This is fixed in the latest version, so I'm going to close this issue!

**Comment by ElYoM** [comment]
Ok thank you for the quick fix.
