### ISSUE TITLE
Docker: Access to path for slashcommandbuuilder dll denied

### ISSUE THREAD

**Issue by jeversol** [darkalfx/requestrr#113]
After the breaking change with bang-to-slash, I dug in and worked to get my instance of the bot working again. As far as I can tell, I've done the necessary things (kicked the bot, reinvited it, ensured the permissions are correct etc). But as of now it's not creating the slash commands. When I run a `docker logs` on the container, I see the following log, indicating a problem accessing a dll:

```
Hosting environment: Production
Content root path: /root
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while restarting the bot: Access to the path '/root/tmp/slashcommandsbuilder-e9561124-a34f-4d3e-b489-3e779de1807f.dll' is denied.
      System.IO.IOException: Access to the path '/root/tmp/slashcommandsbuilder-e9561124-a34f-4d3e-b489-3e779de1807f.dll' is denied.
       ---> System.UnauthorizedAccessException: Access to the path '/root/tmp/slashcommandsbuilder-e9561124-a34f-4d3e-b489-3e779de1807f.dll' is denied.
       ---> System.IO.IOException: Permission denied
         --- End of inner exception stack trace ---
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
         at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
         at System.IO.File.Create(String path)
         at Roslyn.Utilities.FileUtilities.CreateFileStreamChecked(Func`2 factory, String path, String paramName)
         --- End of inner exception stack trace ---
         at Roslyn.Utilities.FileUtilities.CreateFileStreamChecked(Func`2 factory, String path, String paramName)
         at Microsoft.CodeAnalysis.FileSystemExtensions.Emit(Compilation compilation, String outputPath, String pdbPath, String xmlDocPath, String win32ResourcesPath, IEnumerable`1 manifestResources, CancellationToken cancellationToken)
         at Requestrr.WebApi.RequestrrBot.SlashCommandBuilder.Build(ILogger logger, DiscordSettings settings) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\SlashCommands\SlashCommandBuilder.cs:line 57
         at Requestrr.WebApi.RequestrrBot.ChatBot.RestartBot(DiscordSettings previousSettings, DiscordSettings newSettings, HashSet`1 currentGuilds) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 171
         at Requestrr.WebApi.RequestrrBot.ChatBot.<Start>b__20_0() in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 95

```

Other than updating the container to the newest tag, nothing has changed from "everything is working fine" to "the bot is not responding to anything" Any suggestions would be great. Thanks!

**Comment by jeversol** [comment]
Duplicate of #106, closing (and switching to linuxserver.io docker image)
