### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by vancityactivist** [darkalfx/requestrr#121]
have had this issue popping up since the command switch. Essentially, the bot will respond, find the media, but the request will always fail. Here's a sample log output:

```
An error while requesting movie "**********" from Ombi: OmbiCreateMovieRequest failed: Internal Server Error - SQLite Error 5: 'database is locked'.

System.Exception: OmbiCreateMovieRequest failed: Internal Server Error - SQLite Error 5: 'database is locked'.

at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
at Requestrr.WebApi.RequestrrBot.DownloadClients.Ombi.OmbiClient.RequestMovieAsync(MovieRequest request, Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Ombi\OmbiClient.cs:line 109
[40m[1m[33mwarn[39m[22m[49m: Requestrr.WebApi.RequestrrBot.ChatBot[0]
Bot has been restarted.
[41m[30mfail[39m[22m[49m: Requestrr.WebApi.RequestrrBot.DownloadClients.Ombi.OmbiClient[0]
```

This will repeat a few times until the request eventually fully fails out.

I've tried reinstalling both Requesttr and Ombi dockers. appdata is on Cache with lots of free space. No other issues across 20 other containers...

Unraid 6.9.2

**Comment by darkalfx** [comment]
Sadly those are the Ombi logs, it seems the Ombi database is somehow locked.

There's nothing I can do about it, I recommend asking in the Ombi discord for further help on this matter.
