### ISSUE TITLE
 Can not add property Movies to Newtonsoft.Json.Linq.JObject

### ISSUE THREAD

**Issue by y0da822** [darkalfx/requestrr#127]
I wanted to upgrade the docker image I had, and after I removed the container and image, I ran docker run to get a new image and create new container and get this message

Unhandled exception. System.ArgumentException: Can not add property Movies to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JObject.Add(String propertyName, JToken value)
   at Requestrr.WebApi.SettingsFileUpgrader.Upgrade(String settingsFilePath) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\SettingsFileUpgrader.cs:line 237
   at Requestrr.WebApi.Program.UpdateSettingsFile() in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\Program.cs:line 37
   at Requestrr.WebApi.Program.Main(String[] args) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\Program.cs:line 20

**Comment by darkalfx** [comment]
Your settings file got corrupted somehow, you should delete it and start from scratch

**Comment by y0da822** [comment]
That stinks - no big deal.  Deleting the json files worked.  Thanks
