### ISSUE TITLE
Error while searching movies with title

### ISSUE THREAD

**Issue by sirmaestro** [darkalfx/requestrr#128]
Getting this error when requesting movie

I can request other movies such as "apex" and "army of thieves" fine. But for some reason it has trouble processing "dawn of the dead".

Environment: Docker
Version: 2.1.1

```
[41m[30mfail[39m[22m[49m: Requestrr.WebApi.RequestrrBot.ChatBot[0]
Error while searching movies with title dawn of the dead : Bad request: 400
DSharpPlus.Exceptions.BadRequestException: Bad request: 400
at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable`1 attachments)
at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)
at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.ShowMovieSelection(MovieRequest request, IReadOnlyList`1 movies) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 31
at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 41
at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle99999(InteractionContext ctx, String movieTitle)
[2021-11-06 00:05:22 +13:00] [104 /EventHandler] [Warn ] An event handler for COMPONENT_INTERACTED took too long to execute. Defined as "DiscordComponentInteractionCreatedHandler(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.ComponentInteractionCreateEventArgs)" located in "Requestrr.WebApi.RequestrrBot.ChatBot".
```

**Comment by Excelling-At-Excel** [comment]
@sirmaestro 
Were you ever able to find a resolution to this error?

**Comment by sirmaestro** [comment]
No, I still get this error to this day. Maybe something wrong with the metadata for this movie?

**Comment by ExorDG** [comment]
Encountered this error when requesting "american president".

**Comment by owenselles** [comment]
same getting when trying the fast x

**Comment by soulphish** [comment]
I am getting this error with "hitchhikers guide to the galaxy"
Requestrr version 2.1.2

**Comment by ExorDG** [comment]
I was able to work around this by replacing Sonarr/Radarr to Overseerr in Requestrr. No longer getting that error. I think there's something broken when requesting directly to Sonarr/Radarr for some titles.

**Comment by SrDu001** [comment]
Im getting this error suddenly with EVERY request, was working fine days ago.

**Comment by spicerackk** [comment]
Noticed the same issue today myself, although I have been having issues with it working for the last 2 months or so but hadn't had time to sit down and look at what was happening. 

I'm getting the below:

`fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while searching movies with title planes, trains and automobiles : Bad request: 400
      DSharpPlus.Exceptions.BadRequestException: Bad request: 400
         at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.ShowMovieSelection(MovieRequest request, IReadOnlyList`1 movies) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 31
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 41
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle0(InteractionContext ctx, String movieTitle)
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.`
      
The last two lines are concerning, it appears to me with my limited knowledge that Requestrr is restarting after each failed request. 

All it shows in Discord is Request Bot | Sending.....

**Comment by Bicravland** [comment]
Getting the same error as mentionned above since yesterday night

**Comment by basvroegop** [comment]
Tagging along, started getting the same error today. Figured it had to do with the recent update on Docker, but it persists after rolling back to the previous version.

**Comment by cjannusch** [comment]
Tagging along to say I am having this happen as of today too.  Tried a rollback and didn't have any luck, maybe a change with the discord api?

**Comment by SrDu001** [comment]
> @SrDu001 Samething happened to my setup, have you found a solution from your end?

Yes, I was using the latest version on Docker hub from linuxserver but I did not notice was deprecated. So I changed in my dockerfile from `lscr.io/linuxserver/requestrr:latest` to `darkalfx/requestrr:latest` an now im having the version 2.1.3

The version 2.1.2 says `© 2024 Requestrr (v2.1.2)` which leads to you to think it's the latest version

![image](https://github.com/darkalfx/requestrr/assets/43072051/a4a54bbf-5156-4a6f-9ef9-205ee38340df)

**Comment by obadaahmar** [comment]
Forcing an update to the container fixed the issue for me.

**Comment by zanthium** [comment]
Lmao happy to see all of us running into this at the same time and realizing there was an update. I just pushed the new update and it fixed it and was going to post here. However SrDu001 and obadaahmar beat me to it.

**Comment by mayur2281** [comment]
Yes faced the same issue yesterday, fixed it by updating.
