### ISSUE TITLE
Bot not showing any prompts for slash commands in Discord

### ISSUE THREAD

**Issue by DeathGambit** [darkalfx/requestrr#138]
Requestrr Image: darkalfx/requestrr
Version: 2.1.1

What's happening?

- Created a discord bot as instructed in wiki
- Added overseerr as source for TV and Movies
- "Test Settings" button in UI reports "The specified settings are valid" for Chat Client, Movies and TV Shows
- After adding bot in discord, there is no prompt for any of the bot commands, not even `/`
- Check attached Logdump

Logdump:
```
Hosting environment: Production
Content root path: /root
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed: restarting bot
[2021-12-20 15:48:35 +05:30] [0   /            ] [Crit ] There was an error registering application commands: Invalid Form Body
DSharpPlus.Exceptions.BadRequestException: Bad request: 400
   at DSharpPlus.Net.DiscordApiClient.BulkOverwriteGuildApplicationCommandsAsync(UInt64 application_id, UInt64 guild_id, IEnumerable`1 commands)
   at DSharpPlus.SlashCommands.SlashCommandsExtension.<>c__DisplayClass38_0.<<RegisterCommands>b__0>d.MoveNext()
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
```

**Comment by Ronniie** [comment]
Hi! Any updates on this? Receiving this issue as well.
