### ISSUE TITLE
Bot was working fine, nothing changed, overnight getting 401 error

### ISSUE THREAD

**Issue by cryingcoraline** [darkalfx/requestrr#149]
`fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while searching tv shows with title test : Unauthorized: 401
      DSharpPlus.Exceptions.UnauthorizedException: Unauthorized: 401
         at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable``1 attachments)
         at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)`
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordTvShowUserInterface.ShowTvShowSelection(TvShowRequest request, IReadOnlyList``1 searchedTvShows) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordTvShowUserInterface.cs:line 155
         at Requestrr.WebApi.RequestrrBot.TvShows.TvShowRequestingWorkflow.SearchTvShowAsync(String tvShowName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\TvShows\TvShowRequestingWorkflow.cs:line 45
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.TvByTitle0(InteractionContext ctx, String tvShowTitle)`

tried changing my Token, restarted the server, deleted config files and started all over again, used linuxserver image and darkalfx image, everything gives the same errors

**Comment by cryingcoraline** [comment]
checked the discord server for support and other people are reporting the same i
