### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by Jdbaii** [darkalfx/requestrr#177]
Following the Linux instructions, there is no mention of any dependencies needing to be installed.
I manually installed libssl3 and libssl-dev with apt, but still, no dice.
I also had to chmod +x the binary before it would even try to run, this was not mentioned in the instructions either.

./Requestrr.WebApi
No usable version of libssl was found
Aborted (core dumped)

**Comment by Jdbaii** [comment]
Solved by downloading and building OpenSSL 1.1.1 manually.
It starts now, but there is still an SSL issue once I configure the Discord bot.
`Aug 09 00:15:15 me Requestrr.WebApi[280969]: [2023-08-09 00:15:15 +02:00] [112 /RestError   ] [Error] Request to https://discord.com/api/v9/gateway/bot triggered an HttpException
Aug 09 00:15:15 me Requestrr.WebApi[280969]: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Aug 09 00:15:15 me Requestrr.WebApi[280969]:  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    --- End of inner exception stack trace ---
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellation>
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.Net.RestClient.ExecuteRequestAsync(BaseRestRequest request, RateLimitBucket bucket, TaskCompletionSource`1 ratelimitTcs)
Aug 09 00:15:15 me Requestrr.WebApi[280969]: [2023-08-09 00:15:15 +02:00] [102 /ConnectionFa] [Error] Connection attempt failed, retrying in 60s
Aug 09 00:15:15 me Requestrr.WebApi[280969]: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
Aug 09 00:15:15 me Requestrr.WebApi[280969]:  ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    --- End of inner exception stack trace ---
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellation>
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.Net.RestClient.ExecuteRequestAsync(BaseRestRequest request, RateLimitBucket bucket, TaskCompletionSource`1 ratelimitTcs)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.Net.DiscordApiClient.GetGatewayInfoAsync()
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.BaseDiscordClient.GetGatewayInfoAsync(String token)
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.DiscordClient.InternalUpdateGatewayAsync()
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.DiscordClient.InternalConnectAsync()
Aug 09 00:15:15 me Requestrr.WebApi[280969]:    at DSharpPlus.DiscordClient.ConnectAsync(DiscordActivity activity, Nullable`1 status, Nullable`1 idlesince)`

**Comment by Jdbaii** [comment]
In the end found a .deb package on Ubuntu's archive for libssl 1.1.1f which seems to work correctly.
