### ISSUE TITLE
"Error 400: Bad request" when requesting but only for one movie

### ISSUE THREAD

**Issue by droans** [darkalfx/requestrr#184]
I've been receiving a Bad request error for a specific movie, Dawn of the Dead. All other movies and shows seem to be processing correctly - even others with spaces or with similar names.

Here is the logging details:

```
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Error while searching movies with title Dawn of the dead : Bad request: 400
      DSharpPlus.Exceptions.BadRequestException: Bad request: 400
         at DSharpPlus.Net.DiscordApiClient.EditWebhookMessageAsync(UInt64 webhook_id, String webhook_token, String message_id, DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at DSharpPlus.Entities.DiscordInteraction.EditOriginalResponseAsync(DiscordWebhookBuilder builder, IEnumerable`1 attachments)
         at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieUserInterface.ShowMovieSelection(MovieRequest request, IReadOnlyList`1 movies) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieUserInterface.cs:line 31
         at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 41
         at Requestrr.WebApi.RequestrrBot.SlashCommands.RequestGroup.MovieByTitle0(InteractionContext ctx, String movieTitle)
```

**Comment by jgramling17** [comment]
Same.

**Comment by Rain3x** [comment]
I'm having this issue as well. It happens with any movie with the word "dead" in the title. Evil Dead 2, Dawn of the Dead, Shaun of the Dead - all of them.

**Comment by Xikly** [comment]
Hey @Rain3x @droans 
I actually just ran into this issue, after seeing there was a newly released version of Requestrr I updated my current version to the latest; it seemed a fresh install with the same configuration made it work again.

**Comment by hacktek** [comment]
This is definitely a widespread issue of some sort. I just started getting this and as stated above, resetting the bot token didn't fix it.

**Comment by obadaahmar** [comment]
I am getting the same exact error with all requests.

**Comment by edrock200** [comment]
> Hey @Rain3x @droans I actually just ran into this issue, after seeing there was a newly released version of Requestrr I updated my current version to the latest; it seemed a fresh install with the same configuration made it work again.

Thanks for pointing out there is a new version. I ran into this error too, and after seeing your post I updated to the new version and the issue resolved for me. It's pertinent to note if you are running a docker container, and are using linuxserver.io repo, that repo is not getting updated. You have to change your image to use darkalfx/requestrr and change the in container /config mapping to /root/config to wherever you store the configs on your host. 

Doing this upgraded my existing instance and retained all settings, and the 400 errors went away.

**Comment by Rain3x** [comment]
> > Hey @Rain3x @droans I actually just ran into this issue, after seeing there was a newly released version of Requestrr I updated my current version to the latest; it seemed a fresh install with the same configuration made it work again.
> 
> Thanks for pointing out there is a new version. I ran into this error too, and after seeing your post I updated to the new version and the issue resolved for me. It's pertinent to note if you are running a docker container, and are using linuxserver.io repo, that repo is not getting updated. You have to change your image to use darkalfx/requestrr and change the in container /config mapping to /root/config to wherever you store the configs on your host.
> 
> Doing this upgraded my existing instance and retained all settings, and the 400 errors went away.

Can confirm this fixed the issue. I didn't see the update. Thanks!

**Comment by Rain3x** [comment]
> Hey @Rain3x @droans I actually just ran into this issue, after seeing there was a newly released version of Requestrr I updated my current version to the latest; it seemed a fresh install with the same configuration made it work again.

Can confirm this fixed the issue, didn't notice the update. Thank you!
