### ISSUE TITLE
An unexpected error occurred while trying to process your request.

### ISSUE THREAD

**Issue by RemuxKid** [darkalfx/requestrr#55]
`fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      An exception occurred while processing a command: The server responded with error 403: Forbidden
Discord.Net.HttpException: The server responded with error 403: Forbidden
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync(String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.AddReactionAsync(UInt64 channelId, UInt64 messageId, String emoji, RequestOptions options)
   at Discord.Rest.MessageHelper.AddReactionAsync(IMessage msg, IEmote emote, BaseDiscordClient client, RequestOptions options)
   at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieRequestingWorkFlow.GetMovieRequestAsync(Movie movie)
   at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.HandleMovieSelectionAsync(Movie movie)
   at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(String movieName)
   at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieRequestingWorkFlow.HandleMovieRequestAsync(Object[] args)
   at Requestrr.WebApi.RequestrrBot.ChatBot.<>c__DisplayClass18_0.<<ApplyBotConfigurationAsync>b__5>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)`

Having issues when adding through Discord.

All I see is:
`An unexpected error occurred while trying to process your request.`

I've given it permissions in Discord.

I've configured and tested Radarr and Discord bot, but no luck :(

**Comment by Krombopulous45** [comment]
I am also having this issue and I have no way to diagnose it.

**Comment by darkalfx** [comment]
**The server responded with error 403: Forbidden**

This is a permission issue, it means you havent given the bot some permissions, I cannot tell you which are missing.

**Comment by SnkyFrsh** [comment]
Was there ever a solution found for this? Mine was working fine then all of a sudden I keep getting `An unexpected error occurred while trying to process your request.` after clicking the emote to download.
