### ISSUE TITLE
[Overseerr] An unexpected error occurred

### ISSUE THREAD

**Issue by lostage** [darkalfx/requestrr#72]
Requesting a TV show produces the error above. Below is the relevant log entry. My setup in Overseerr is one Plex User (Admin), and the "Default Overseer User ID for requests" setting in Requestrr is empty. Thank you!

`fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient[0]
      An error while requesting movie "Us Again" from Overseerr: OverseerrFindAllUsers failed: Bad Request - {"message":"Unknown query parameter 'take'","errors":[{"path":".query.take","message":"Unknown query parameter 'take'"}]}
System.Exception: OverseerrFindAllUsers failed: Bad Request - {"message":"Unknown query parameter 'take'","errors":[{"path":".query.take","message":"Unknown query parameter 'take'"}]}
   at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 31
   at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.FindLinkedOverseerUserAsync(String userId, String username) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 335
   at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.Requestrr.WebApi.RequestrrBot.Movies.IMovieRequester.RequestMovieAsync(MovieUserRequester requester, Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 198
fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      An exception occurred while processing a command: An error while requesting movie "Us Again" from Overseerr: OverseerrFindAllUsers failed: Bad Request - {"message":"Unknown query parameter 'take'","errors":[{"path":".query.take","message":"Unknown query parameter 'take'"}]}
System.Exception: An error while requesting movie "Us Again" from Overseerr: OverseerrFindAllUsers failed: Bad Request - {"message":"Unknown query parameter 'take'","errors":[{"path":".query.take","message":"Unknown query parameter 'take'"}]}
   at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.Requestrr.WebApi.RequestrrBot.Movies.IMovieRequester.RequestMovieAsync(MovieUserRequester requester, Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 221
   at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.HandleMovieSelectionAsync(Movie movie) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 112
   at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 43
   at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieRequestingWorkFlow.HandleMovieRequestAsync(Object[] args) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieRequestingWorkFlow.cs:line 96
   at Requestrr.WebApi.RequestrrBot.ChatBot.<>c__DisplayClass19_0.<<ApplyBotConfigurationAsync>b__5>d.MoveNext() in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
`

**Comment by darkalfx** [comment]
You'll need to use the develop branch of Overseer until the next release is out (Soon I hear), then you can go back to stable branch.

**Comment by darkalfx** [comment]
Overseerr just released a new version on their stable branch, so I'll close this issue since there will be no more compatibility issues now.
