### ISSUE TITLE
[Overseerr] An unexpected error occurred while trying to process your request. --> When titles are using special characters

### ISSUE THREAD

**Issue by moust4ki** [darkalfx/requestrr#74]
Hello,

Everytime I try to add something with a special character, I have the following error:
`An unexpected error occurred while trying to process your request.`
For example:
`!tv t'choupi à l'école`
I have no issue requesting it directly in Overseerr so it's an issue between Requestrr and Overseerr.

Thanks

**Comment by vember31** [comment]
Can confirm this issue too when using Overseerr as a back-end, and searching for It's Always Sunny in Philadelphia.  Removing the apostrophe results in the query working just fine.

Here's the error from the logs if useful.

**Comment by allquiet-hub** [comment]
Yes I have encountered the same issue.
"#movie Prince of Persia: The Sands of Time" doesnt work
"#movie Prince of Persia The Sands of Time" works.

Follows the error stack:

```
2021-03-07T22:32:21.385243951Z fail: Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient[0]
2021-03-07T22:32:21.385278893Z       An error occurred while searching for movies from Overseerr: OverseerrMovieSearch failed: Bad Request - {"message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters.","errors":[{"path":".query.query","message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters."}]}
2021-03-07T22:32:21.385292464Z System.Exception: OverseerrMovieSearch failed: Bad Request - {"message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters.","errors":[{"path":".query.query","message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters."}]}
2021-03-07T22:32:21.385300536Z    at Requestrr.WebApi.Extensions.HttpResponseMessageExtensions.ThrowIfNotSuccessfulAsync(HttpResponseMessage responseMessage, String message, Func`2 getErrorFunc) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\Extensions\HttpResponseMessageExtensions.cs:line 35
2021-03-07T22:32:21.385307602Z    at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 160
2021-03-07T22:32:21.386488266Z fail: Requestrr.WebApi.RequestrrBot.ChatBot[0]
2021-03-07T22:32:21.386510947Z       An exception occurred while processing a command: An error occurred while searching for movies from Overseerr: OverseerrMovieSearch failed: Bad Request - {"message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters.","errors":[{"path":".query.query","message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters."}]}
2021-03-07T22:32:21.386525508Z System.Exception: An error occurred while searching for movies from Overseerr: OverseerrMovieSearch failed: Bad Request - {"message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters.","errors":[{"path":".query.query","message":"Parameter 'query' must be url encoded. Its value may not contain reserved characters."}]}
2021-03-07T22:32:21.386537923Z    at Requestrr.WebApi.RequestrrBot.DownloadClients.Overseerr.OverseerrClient.SearchMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\DownloadClients\Overseerr\OverseerrClient.cs:line 171
2021-03-07T22:32:21.386549277Z    at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.SearchMoviesAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 91
2021-03-07T22:32:21.386567268Z    at Requestrr.WebApi.RequestrrBot.Movies.MovieRequestingWorkflow.RequestMovieAsync(String movieName) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\Movies\MovieRequestingWorkflow.cs:line 32
2021-03-07T22:32:21.386574240Z    at Requestrr.WebApi.RequestrrBot.ChatClients.Discord.DiscordMovieRequestingWorkFlow.HandleMovieRequestAsync(Object[] args) in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatClients\Discord\DiscordMovieRequestingWorkFlow.cs:line 96
2021-03-07T22:32:21.386610225Z    at Requestrr.WebApi.RequestrrBot.ChatBot.<>c__DisplayClass19_0.<<ApplyBotConfigurationAsync>b__5>d.MoveNext() in D:\Dev\Requestrr\requestrr\Requestrr.WebApi\RequestrrBot\ChatBot.cs:line 169
2021-03-07T22:32:21.386624102Z --- End of stack trace from previous location where exception was thrown ---
2021-03-07T22:32:21.386635517Z    at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
```

**Comment by allquiet-hub** [comment]
@darkalfx if you could please check out this issue

**Comment by darkalfx** [comment]
Fixed in the latest release
