### ISSUE TITLE
Requestrr will not connect to discord

### ISSUE THREAD

**Issue by thefuzzylimpets** [darkalfx/requestrr#79]
I installed it and got everything working fine, and then decided to change the location of the requestrr bot on my pc.  After moving, I cannot get it to connect to discord at all anymore.  test settings says everything is working, but I keep getting this when starting : 
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
Hosting environment: Production
Content root path: C:\Users\Nis_ASty\Documents\requestrr-win-x64
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
I have tried deleting requestrr, as well as my discord application and nothing is working.

**Comment by thefuzzylimpets** [comment]
*Also forgot to mention that I am not using reverse proxy or https, nor are they reflected in the settings

**Comment by horford** [comment]
I'm also getting a similar error, this is my first setup though. I'm using Unraid with Docker. I cant seem to get the discord bot running. 

Application started. Press Ctrl+C to shut down.
[40m[1m[33mwarn[39m[22m[49m: Requestrr.WebApi.RequestrrBot.ChatBot[0]
Bot configuration changed/not connected to Discord: restarting bot
[40m[1m[33mwarn[39m[22m[49m: Requestrr.WebApi.RequestrrBot.ChatBot[0]
Bot has been restarted.

**Comment by NiNiyas** [comment]
Experiencing the same issue. I am on docker using hotio's latest version image.

```Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      [Discord] 
      Discord.WebSocket.GatewayReconnectException: Server requested a reconnect
         at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      [Discord] Disconnecting from Discord due to error
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      [Discord] Failed to resume previous session
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      [Discord] 
      System.Exception: WebSocket connection was closed
       ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
         at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
         at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
         at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
         at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken)
         --- End of inner exception stack trace ---
         at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      [Discord] Disconnecting from Discord due to error
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.``

**Comment by waisenflix** [comment]
Same here.

**Comment by Sariden342** [comment]
Same problem for me. Running on Windows Server 2016 VM. The bot shows as active in my discord but I can't successfully !ping it.

Hosting environment: Production
Content root path: C:\Requestrr
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by MrLiink49** [comment]
Same for me : running in docker (image from linuxserver.io)


[services.d] done.
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {d0aeb346-a230-4dd5-8d21-30d4ac1f61f6} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app/requestrr/bin
Now listening on: http://[::]:4545
Application started. Press Ctrl+C to shut down.
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot configuration changed/not connected to Discord: restarting bot
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]
      Bot has been restarted.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

**Comment by darkalfx** [comment]
Use the official image and report the bug to linuxserver, I don't maintain that image.

**Comment by BioHazard2000** [comment]
I am getting the same errors using your image on a Synology box.  The errors started on the 25th.

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]                                                                                                                          
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.                   
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]                                                                                                                                                              
      Bot configuration changed: restarting bot                                                                                                                                                             
Hosting environment: Production                                                                                                                                                                             
Content root path: /root                                                                                                                                                                                    
Now listening on: http://[::]:4545                                                                                                                                                                          
Application started. Press Ctrl+C to shut down.                                                                                                                                                             
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]                                                                                                                                                              
      Bot has been restarted.                                                                                                                                                                               
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]                                                                                                                                                              
      Bot configuration changed: restarting bot                                                                                                                                                             
warn: Requestrr.WebApi.RequestrrBot.ChatBot[0]                                                                                                                                                              
      Bot has been restarted.

My Discord bot doesn't talk to anything anymore but all the settings test fine.

What else can I give you to help diagnose this issue?

**Comment by darkalfx** [comment]
Those logs look normal to me.

The bot was upgraded to use slash commands, so you'll probably have to kick and re-invite your bot with the new link in the web portal of Requestrr.

Then the new commands work by typing /

**Comment by BioHazard2000** [comment]
Worked like a charm.

 

Thanks for your help and good work with this app.  It’s very friendly and these new /commands are slick!
