### ISSUE TITLE
Add step by step guide to setup development environment

### ISSUE THREAD

**Issue by WormChickenWizard** [darkalfx/requestrr#84]
I'm wanting to contribute back to the project but I'm having some issues setting up the development environment
```
> Requestrr@1.0.17 install:clean
> rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Requestrr@1.0.17
npm ERR! Found: react@16.8.4
npm ERR! node_modules/react
npm ERR!   react@"16.8.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=16.8.6" from react-dropdown-select@4.7.4
npm ERR! node_modules/react-dropdown-select
npm ERR!   react-dropdown-select@"^4.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/worm/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/worm/.npm/_logs/2021-04-25T15_13_33_871Z-debug.log
```
Looks like a dependency issue to me but I'm not experienced in JS. For future reference, could you add/elaborate more on how to setup the development environment? Maybe in a separate markdown file to keep readme.md relatively minimal if that's what you're shooting for.

**Comment by darkalfx** [comment]
I would love to, however the details change depending on what OS you're developing on.

In short, you need NodeJS and the .NET SDK 5.0.

You also need to install the "windows-build-tools" NPM package if you're in Windows.

I also recommend usinf VSCodw which is what I use.

**Comment by WormChickenWizard** [comment]
OK fair enough. I installed the equivalent packages for everything except the windows-build-tools and im still getting the same error. With these other files do you have any idea what dependency issue i'm having?

~/.npm/_logs/2021-04-25T23_55_31_890Z-debug.log
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.9.0
2 info using node@v15.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/home/worm/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 6ms
18 timing npm:load:configload Completed in 6ms
19 timing npm:load:setTitle Completed in 0ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 1ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 10ms
25 timing config:load:flatten Completed in 2ms
26 timing arborist:ctor Completed in 1ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 18ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 silly fetch manifest @types/googlemaps@3.30.18
32 http fetch GET 304 https://registry.npmjs.org/@types%2fgooglemaps 113ms (from cache)
33 silly fetch manifest @types/markerclustererplus@2.1.33
34 http fetch GET 304 https://registry.npmjs.org/@types%2fmarkerclustererplus 50ms (from cache)
35 silly fetch manifest @types/react@16.8.7
36 http fetch GET 304 https://registry.npmjs.org/@types%2freact 48ms (from cache)
37 silly fetch manifest typescript@3.3.3333
38 http fetch GET 304 https://registry.npmjs.org/typescript 92ms (from cache)
39 silly fetch manifest chart.js@2.7.3
40 http fetch GET 304 https://registry.npmjs.org/chart.js 66ms (from cache)
41 silly fetch manifest classnames@2.2.6
42 http fetch GET 304 https://registry.npmjs.org/classnames 59ms (from cache)
43 silly fetch manifest moment@2.24.0
44 http fetch GET 304 https://registry.npmjs.org/moment 51ms (from cache)
45 silly fetch manifest node-sass@4.12.0
46 http fetch GET 304 https://registry.npmjs.org/node-sass 48ms (from cache)
47 silly fetch manifest nouislider@13.1.1
48 http fetch GET 304 https://registry.npmjs.org/nouislider 39ms (from cache)
49 silly fetch manifest react@16.8.4
50 http fetch GET 304 https://registry.npmjs.org/react 66ms (from cache)
51 silly fetch manifest react-chartjs-2@2.7.4
52 http fetch GET 304 https://registry.npmjs.org/react-chartjs-2 50ms (from cache)
53 silly fetch manifest react-dom@16.8.4
54 http fetch GET 304 https://registry.npmjs.org/react-dom 63ms (from cache)
55 silly fetch manifest react-copy-to-clipboard@5.0.1
56 http fetch GET 304 https://registry.npmjs.org/react-copy-to-clipboard 36ms (from cache)
57 silly fetch manifest react-datetime@2.16.3
58 http fetch GET 304 https://registry.npmjs.org/react-datetime 33ms (from cache)
59 silly fetch manifest react-dropdown-select@^4.1.1
60 http fetch GET 304 https://registry.npmjs.org/react-dropdown-select 40ms (from cache)
61 silly fetch manifest prop-types@>=15.7.2
62 http fetch GET 304 https://registry.npmjs.org/prop-types 28ms (from cache)
63 silly fetch manifest react@>=16.8.6
64 timing idealTree Completed in 1019ms
65 timing command:install Completed in 1032ms
66 verbose stack Error: unable to resolve dependency tree
66 verbose stack     at Arborist.[failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1210:25)
66 verbose stack     at Arborist.[loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1187:34)
66 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:891:11)
66 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:217:7)
66 verbose stack     at async Promise.all (index 1)
66 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:5)
66 verbose stack     at async Install.install (/usr/lib/node_modules/npm/lib/install.js:137:5)
67 verbose cwd /home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp
68 verbose Linux 5.11.14-1-MANJARO
69 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
70 verbose node v15.14.0
71 verbose npm  v7.9.0
72 error code ERESOLVE
73 error ERESOLVE unable to resolve dependency tree
74 error
75 error While resolving: Requestrr@1.0.17
75 error Found: react@16.8.4
75 error node_modules/react
75 error   react@"16.8.4" from the root project
75 error
75 error Could not resolve dependency:
75 error peer react@">=16.8.6" from react-dropdown-select@4.7.4
75 error node_modules/react-dropdown-select
75 error   react-dropdown-select@"^4.1.1" from the root project
75 error
75 error Fix the upstream dependency conflict, or retry
75 error this command with --force, or --legacy-peer-deps
75 error to accept an incorrect (and potentially broken) dependency resolution.
75 error
75 error See /home/worm/.npm/eresolve-report.txt for a full report.
76 verbose exit 1
```
~/.npm/eresolve-report.txt
```
# npm resolution error report

2021-04-25T23:55:31.885Z

While resolving: Requestrr@1.0.17
Found: react@16.8.4
node_modules/react
  react@"16.8.4" from the root project

Could not resolve dependency:
peer react@">=16.8.6" from react-dropdown-select@4.7.4
node_modules/react-dropdown-select
  react-dropdown-select@"^4.1.1" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "16.8.4",
    "whileInstalling": {
      "name": "Requestrr",
      "version": "1.0.17",
      "path": "/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp"
    },
    "location": "node_modules/react",
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "16.8.4",
        "from": {
          "location": "/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react",
    "spec": "16.8.4",
    "from": {
      "location": "/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": ">=16.8.6",
    "error": "INVALID",
    "from": {
      "name": "react-dropdown-select",
      "version": "4.7.4",
      "whileInstalling": {
        "name": "Requestrr",
        "version": "1.0.17",
        "path": "/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp"
      },
      "location": "node_modules/react-dropdown-select",
      "dependents": [
        {
          "type": "prod",
          "name": "react-dropdown-select",
          "spec": "^4.1.1",
          "from": {
            "location": "/home/worm/Desktop/requestrr/Requestrr.WebApi/ClientApp"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

**Comment by darkalfx** [comment]
Try to force the react-dropdown-select package to version 4.1.1 and see if it fixes it.
